config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'sign_up' => 'sign_up#index'
  post 'sign_up' => 'sign_up#new'
  get '/verify_account/:id', to: 'sign_up#verify_account', as: 'verify_account'
  get '/about' => 'sign_up#about'
  root 'organisations#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :organisations do
    resources :employees
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  include BCrypt
  belongs_to :organisation

  enum role: { system: 'system', admin: 'admin', employee: 'employee' }
  validates :avatar, :fname, :lname, :birthday, :role, presence: true
  validates :password, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }

  def password
    @password ||= Password.new(password_hash) unless password_hash.to_s.strip.empty?
  end

  def password=(new_password)
    unless new_password.to_s.strip.empty?
      @password = Password.create(new_password)
      self.password_hash = @password
    end
  end
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :employees, dependent: :destroy

  validates_presence_of :name, :logo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  helper_method :logged_in?, :current_user

  def current_user
    Employee.find_by(id: session[:user_id])
  end

  def require_user_logged_in!
    # allows only logged in user
    redirect_to login_path, alert: 'You must be signed in' if current_user.nil?
  end

  def logged_in?
    !current_user.nil?
  end

  private

  def user_not_authorized
    flash[:warning] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # allows only logged in users
  before_action :require_user_logged_in!
  before_action :set_employee, only: %i[show edit update destroy]

  def show; end

  def edit
    @roles = Employee.roles.map { |key, value| [key, value] }
  end

  def update
    if @employee.update(update_employee_params)
      redirect_to [@employee.organisation, @employee]
    else
      @roles = Employee.roles.map { |key, value| [key, value] }
      render :edit
    end
  end

  def destroy
    @employee.destroy
    redirect_to @employee.organisation
  end

  def new
    @organisation = Organisation.find(params[:organisation_id])
    @employee = @organisation.employees.build
    @roles = Employee.roles.map { |key, value| [key, value] }
  end

  def create
    @organisation = Organisation.find(params[:organisation_id])
    @employee = @organisation.employees.create(create_employee_params)

    if @employee.save
      redirect_to [@employee.organisation, @employee]
    else
      @organisation = Organisation.find(params[:organisation_id])
      @roles = Employee.roles.map { |key, value| [key, value] }
      render :new
    end
  end

  private

  def set_employee
    @employee = Employee.find(params[:id])
    authorize @employee
  end

  def update_employee_params
    params.required(:employee).permit(:fname, :lname, :avatar, :birthday, :email, :password, :role)
          .with_defaults(verified: true)
  end

  def create_employee_params
    params.required(:employee).permit(:fname, :lname, :avatar, :birthday, :email, :password, :role)
          .with_defaults(verified: true, role: Employee.roles[:employee], password: '123456')
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  # allows only logged in users
  before_action :require_user_logged_in!
  before_action :set_organisation, only: %i[show edit update destroy]

  def index
    @organisations = Organisation.all
  end

  def show; end

  def edit; end

  def update
    if @organisation.update(organisation_params)
      redirect_to @organisation
    else
      render :edit
    end
  end

  def destroy
    @organisation.destroy
    redirect_to organisations_path
  end

  def new
    @organisation = Organisation.new
  end

  def create
    @organisation = Organisation.new(organisation_params)

    if @organisation.save
      redirect_to @organisation
    else
      render :new
    end
  end

  private

  def set_organisation
    @organisation = Organisation.find(params[:id])
    authorize @organisation
  end

  def organisation_params
    params.required(:organisation).permit(:name, :logo)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = Employee.find_by(email: params[:session][:email].downcase)

    if @user.present? && @user.password.is_password?(params[:session][:password])
      if @user.verified
        # sets up user.id sessions
        session[:user_id] = @user.id
        redirect_to root_path, notice: 'Logged in successfully'
      else
        flash[:danger] = 'Account has not been verified yet'
        render :new
      end
    else
      flash[:danger] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    # deletes user session
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged Out'
  end
end

app/controllers/sign_up_controller.rb
class SignUpController < ApplicationController
  def index
    @employee = Employee.new
    @organisations = Organisation.all.map { |organisation| [organisation.name, organisation.id] }
  end

  def new
    @employee = Employee.new(sign_up_params)

    if @employee.save
      WelcomeMailer.with(user: @employee).welcome_email.deliver_now
      # deliver_now is provided by ActiveJob.
      redirect_to login_path, notice: 'Successfully created account'
    else
      @organisations = Organisation.all.map { |organisation| [organisation.name, organisation.id] }
      render :index
    end
  end

  def verify_account
    @employee = Employee.find(params[:id])
    @employee.update(verified: true)

    redirect_to login_path
  end

  def about
    render 'sign_up/about'
  end

  private

  def sign_up_params
    params.require(:employee).permit(:fname, :password, :lname, :email, :organisation_id, :role, :birthday,
                                     :avatar)
          .with_defaults(role: Employee.roles[:employee])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/views/employees/_form.html.erb
<%= form_with model: [employee.organisation, employee] do |form|  %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fname %>
    <%= form.text_field :fname %>
  </div>

  <div class="field">
    <%= form.label :lname %>
    <%= form.text_field :lname %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.text_area :avatar %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_field :birthday, as: :date, value: form.object.try(:strftime,"%d/%m/%Y") %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_area :email %>
  </div>

  <div>
    <%= form.label :role %>
    <%= form.select :role, @roles %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', [@employee.organisation, @employee] %> |
<%= link_to 'Back', organisation_path(@employee.organisation) %>

app/views/employees/new.html.erb
<h1>Creating Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', [@employee.organisation, @employee] %> |
<%= link_to 'Back', organisation_path(@employee.organisation) %>

app/views/employees/show.html.erb
<p>
  <strong>Name:</strong>
  <%= "#{@employee.fname} #{@employee.lname}" %>
</p>
<p>
  <strong>Avatar:</strong>
  <img src="<%= @employee.avatar %>" style="width: 60px; height: 60px;"/>
</p>
<p>
  <strong>Birthday:</strong>
  <%= @employee.birthday.strftime("%d/%m/%Y") %>
</p>
<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>
<p>
  <strong>Role:</strong>
  <%= Employee.roles.key(@employee.role) %>
</p>

<% if policy(@employee).update? %>
  <%= link_to 'Edit', edit_organisation_employee_path(@employee.organisation,@employee) %> |
<% end %>
<%= link_to 'Back', organisation_path(@employee.organisation) %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse" style="margin-top: 30px">
  <div class="container">
    <% if logged_in? %>
    <%= link_to 'Log out', logout_path, method: :delete %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/organisations/_form.html.erb
<%= form_with model: organisation do |form|  %>
  <% if organisation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organisation.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% organisation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :logo %>
    <%= form.text_area :logo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/organisations/edit.html.erb
<h1>Editing Organisation</h1>

<%= render 'form', organisation: @organisation %>

<%= link_to 'Show', @organisation %> |
<%= link_to 'Back', organisations_path %>

app/views/organisations/index.html.erb
<h1>Organisations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Logo</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @organisations.each do |organisation| %>
      <% if policy(organisation).show? %>
        <tr>
          <td><%= organisation.name %></td>
          <td><img src="<%= organisation.logo %>" style="width: 60px; height: 60px;"/></td>
          <td><%= link_to 'Show', organisation %></td>
          <% if policy(organisation).update? %>
            <td><%= link_to 'Edit', edit_organisation_path(organisation) %></td>
          <% end %>
          <% if policy(organisation).destroy? %>
            <td><%= link_to 'Destroy', organisation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<% if policy(Organisation.new).create? %>
  <%= link_to 'New Organisation', new_organisation_path %>
<% end %>

app/views/organisations/new.html.erb
<h1>Creating Organisation</h1>

<%= render 'form', organisation: @organisation %>

<%= link_to 'Show', @organisation %> |
<%= link_to 'Back', organisations_path %>

app/views/organisations/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @organisation.name %>
</p>

<p>
  <strong>Logo:</strong>
  <img src="<%= @organisation.logo %>" style="width: 60px; height: 60px;"/>
</p>

<h2>Employees</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @organisation.employees.each do |employee| %>
      <% if policy(employee).show? %>
        <tr>
          <td><%= "#{employee.fname} #{employee.lname}" %></td>
          <td><%= employee.email %></td>
          <td><%= link_to 'Show', organisation_employee_path(employee.organisation,employee) %></td>
          <% if policy(employee).update? %>
            <td><%= link_to 'Edit', edit_organisation_employee_path(employee.organisation,employee) %></td>
          <% end %>
          <% if policy(employee).destroy? %>
            <td><%= link_to 'Destroy', [employee.organisation, employee], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<% if policy(@organisation.employees.build).create? %>
  <%= link_to 'New Employee', new_organisation_employee_path(@organisation) %>
<% end %>

<br />
<br />
<br />
<br />
<% if policy(@organisation).update? %>
  <%= link_to 'Edit', edit_organisation_path(@organisation) %> |
<% end %>
<%= link_to 'Back', organisations_path %>

app/views/sign_up/about.html.erb
<h1>This is About page</h1>

app/views/sign_up/index.html.erb
<div class="container">
  <div class="row">
    <h1 class="title">Signup</h1>
  </div>
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <%= form_with model: @employee, url: sign_up_path, method: :post do |f| %>
        <div class="form-group">
          <%= f.label :fname, 'First Name' %>
          <%= f.text_field :fname, placeholder: "Enter your first name", class: "form-control" %>

          <% @employee.errors.full_messages_for(:fname).each do |message| %>
              <div><%= message %></div>
          <% end %>
        </div>
        <div class="form-group">
          <%= f.label :lname, 'Last Name' %>
          <%= f.text_field :lname, placeholder: "Enter your last name", class: "form-control" %>

          <% @employee.errors.full_messages_for(:lname).each do |message| %>
              <div><%= message %></div>
          <% end %>
        </div>
        <div class="form-group">
          <%= f.label :birthday, 'Birthday' %>
          <%= f.date_field :birthday, placeholder: "dd/MM/YYYY", as: :date, value: f.object.try(:strftime,"%d/%m/%Y") %>

          <% @employee.errors.full_messages_for(:birthday).each do |message| %>
              <div><%= message %></div>
          <% end %>
        </div>
        <div class="form-group">
          <%= f.label :avatar, 'Avatar' %>
          <%= f.text_field :avatar, class: "form-control" %>

          <% @employee.errors.full_messages_for(:avatar).each do |message| %>
              <div><%= message %></div>
          <% end %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, placeholder: "Enter your email", class: "form-control" %>

          <% @employee.errors.full_messages_for(:email).each do |message| %>
              <div><%= message %></div>
          <% end %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, placeholder: "Enter your password",
            class: "form-control" %>

          <% @employee.errors.full_messages_for(:password).each do |message| %>
              <div><%= message %></div>
          <% end %>
        </div>
        <div>
          <%= f.label :organisation_id %>
          <%= f.select :organisation_id, @organisations %>
        </div>
        <div class="text-center">
          <%= f.submit "Signup", class: "btn btn-info col-lg-12" %>
        </div>
      <% end %>
    </div>
  </div>
</div>